# Generated by Django 4.1.3 on 2023-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_target_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='posts.question'),
        ),
    ]
