# Generated by Django 4.0.4 on 2022-09-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_author_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='target_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_target_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='posts.question'),
        ),
    ]
