# Generated by Django 4.0.4 on 2022-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
