# Generated by Django 4.0.4 on 2022-09-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_question_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
