# Generated by Django 4.0.4 on 2022-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_question_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
