# Generated by Django 4.0.4 on 2022-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_question_chatroom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chatroom_password',
            field=models.CharField(max_length=30),
        ),
    ]
