# Generated by Django 4.0.4 on 2022-10-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_question_chatroom_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author_profile',
        ),
    ]
