# Generated by Django 4.1.3 on 2022-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_question_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjectiveList',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NounList',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
