# Generated by Django 4.1.3 on 2022-12-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_adjectivelist_nounlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chatroom_password',
        ),
    ]
