# Generated by Django 4.1.2 on 2023-04-12 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_apnsdevices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APNsDevices',
            new_name='APNsDevice',
        ),
    ]
