# Generated by Django 4.0.4 on 2022-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
