# Generated by Django 4.1.2 on 2023-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_apnsdevices_apnsdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnsdevice',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
