# Generated by Django 4.0.4 on 2022-10-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_restrictedusername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestrictedUsername',
            new_name='ForbiddenUsername',
        ),
    ]
