# Generated by Django 4.0.4 on 2022-10-10 17:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_restrictedusername_forbiddenusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='profile/'),
        ),
    ]
