# Generated by Django 4.0.4 on 2022-10-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forbiddenusername',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
