# Generated by Django 4.1.3 on 2022-11-26 12:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_forbiddenusername_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_background.png', force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='background/'),
        ),
    ]
