# Generated by Django 4.1.3 on 2022-12-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_username_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedIp',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
