# Generated by Django 4.1.3 on 2023-03-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0012_delete_bannedip_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=40, null=True)),
                ('refresh_token_expiration_date', models.DateTimeField(null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
        migrations.DeleteModel(
            name='TokenExpiration',
        ),
    ]
