# Generated by Django 4.1.3 on 2023-03-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tokendata_delete_tokenexpiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendata',
            name='refresh_token',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='refresh_token_expiration_date',
            field=models.DateTimeField(),
        ),
    ]
