# Generated by Django 4.1.3 on 2022-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_context_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymity_status',
            field=models.BooleanField(default=False),
        ),
    ]
