# Generated by Django 4.1.3 on 2022-12-07 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_post_anonymity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='community_post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
