# Generated by Django 4.1.3 on 2022-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymity_status',
            field=models.BooleanField(default=False),
        ),
    ]
