# Generated by Django 4.1.3 on 2022-12-11 18:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, default='1', force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='community/'),
        ),
    ]
