# Generated by Django 4.1.3 on 2022-12-11 19:12

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='community/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_file', to='community.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
