# Generated by Django 4.0.4 on 2022-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjectivelist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nounlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='adjectivelist',
            name='word',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nounlist',
            name='ward',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
