# Generated by Django 4.0.4 on 2022-09-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_adjectivelist_id_remove_nounlist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nounlist',
            old_name='ward',
            new_name='word',
        ),
    ]
