# Generated by Django 4.0.4 on 2022-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatroom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='key',
            field=models.CharField(default='1', max_length=40),
        ),
    ]
