# Generated by Django 4.0.4 on 2022-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatroom_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='key',
            field=models.CharField(max_length=40),
        ),
    ]
