# Generated by Django 4.0.4 on 2022-10-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chatroom_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='password',
        ),
    ]
