# Generated by Django 4.0.4 on 2022-10-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chat_sender_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chats.chatroom'),
        ),
    ]
