# Generated by Django 4.0.4 on 2022-10-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_chat_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender_profile',
        ),
    ]
