# Generated by Django 4.0.4 on 2022-10-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_restrictedusername_forbiddenusername'),
        ('chats', '0010_remove_chat_sender_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender_profile', to='users.profile'),
        ),
    ]
