# Generated by Django 4.1.3 on 2023-04-10 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='profile/')),
                ('background_image', django_resized.forms.ResizedImageField(crop=None, default='default_background.png', force_format=None, keep_meta=True, quality=65, scale=0.5, size=[1920, 1080], upload_to='background/')),
                ('profile_message', models.CharField(blank=True, max_length=50, null=True)),
                ('deactivated_status', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('recent_access_ip', models.CharField(blank=True, max_length=20)),
                ('follower', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
