# Generated by Django 4.2.2 on 2023-07-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_ranking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ranking_status',
            field=models.BooleanField(default=True),
        ),
    ]
