# Generated by Django 4.1.2 on 2023-04-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='refused_date',
            field=models.DateTimeField(null=True),
        ),
    ]
