# Generated by Django 4.1.2 on 2023-04-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0003_question_refused_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjectiveList',
        ),
        migrations.DeleteModel(
            name='NounList',
        ),
        migrations.RemoveField(
            model_name='question',
            name='nickname',
        ),
    ]
