# Generated by Django 4.1.2 on 2023-06-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_follower_alter_profile_following'),
        ('chatty', '0005_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_author_profile', to='user.profile'),
        ),
    ]
