# Generated by Django 4.1.2 on 2023-06-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0006_alter_question_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='author_profile',
        ),
    ]
