# Generated by Django 4.1.2 on 2023-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0007_rename_author_question_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
